name: davar
description: Davar - helps memorize words or sentences and learning new language.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  file_picker: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 5.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  get_it: ^7.2.0
  path_provider: ^2.0.11
  permission_handler: 9.2.0
  provider: ^6.0.3
  share_plus: ^4.0.10+1
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3+1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mockito: ^5.3.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/onboard_1.png
    - assets/images/onboard_2.png
    - assets/images/onboarding3.jpg
    - assets/images/quiz_bg.jpg
    - assets/images/cherry.png
    - assets/images/orange.png
    - assets/images/orange_melange.png
    - assets/images/wathermel.png
    - assets/images/flutter_logo.png
