name: davar
description: Davar - helps memorize words or sentences and learning new language.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  file_picker: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 5.0.2
  get_it: ^7.2.0
  path_provider: ^2.0.11
  permission_handler: 9.2.0
  provider: ^6.0.3
  share_plus: ^4.0.10+1
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/onboard_1.png
    - assets/images/onboard_2.png
    - assets/images/onboarding3.jpg
    - assets/images/quiz_bg.jpg
