// Mocks generated by Mockito 5.3.1 from annotations
// in davar/test/data/repositories/authentication_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:davar/src/domain/i_secure_storage.dart' as _i2;
import 'package:davar/src/domain/i_user_local_db.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ISecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorage extends _i1.Mock implements _i2.ISecureStorage {
  @override
  _i3.Future<void> persistEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #persistEmail,
          [email],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> persistPassword(String? pwd) => (super.noSuchMethod(
        Invocation.method(
          #persistPassword,
          [pwd],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> persistToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #persistToken,
          [token],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<String?> getEmail() => (super.noSuchMethod(
        Invocation.method(
          #getEmail,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
        returnValueForMissingStub: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
  @override
  _i3.Future<String?> getPassword() => (super.noSuchMethod(
        Invocation.method(
          #getPassword,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
        returnValueForMissingStub: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
  @override
  _i3.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
        returnValueForMissingStub: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
  @override
  _i3.Future<void> deletePassword() => (super.noSuchMethod(
        Invocation.method(
          #deletePassword,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> deleteEmail() => (super.noSuchMethod(
        Invocation.method(
          #deleteEmail,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [IUserLocalDb].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDb extends _i1.Mock
    implements _i4.IUserLocalDb<Map<String, dynamic>> {
  @override
  _i3.Future<int> createUser(Map<String, dynamic>? newUser) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [newUser],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
  @override
  _i3.Future<List<Map<String, dynamic>?>> selectUser({
    required List<String>? where,
    required List<dynamic>? values,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectUser,
          [],
          {
            #where: where,
            #values: values,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>?>>.value(
            <Map<String, dynamic>?>[]),
        returnValueForMissingStub:
            _i3.Future<List<Map<String, dynamic>?>>.value(
                <Map<String, dynamic>?>[]),
      ) as _i3.Future<List<Map<String, dynamic>?>>);
  @override
  _i3.Future<int> rawUpdateUser({
    required List<String>? columns,
    required List<dynamic>? values,
    required int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawUpdateUser,
          [],
          {
            #columns: columns,
            #values: values,
            #id: id,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
  @override
  _i3.Future<int> updateUser(
    Map<String, dynamic>? u,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [
            u,
            userId,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
  @override
  _i3.Future<int> deleteUser(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
